# Generated by Django 3.0.2 on 2020-02-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_itle',
            new_name='song_title',
        ),
    ]
